FROM centos:centos7.5.1804

RUN \
    yum update -y \
    && yum -y install \
        https://centos7.iuscommunity.org/ius-release.rpm \
    && 
    && yum install -y \
        python36u \
        python36u-pip
