[INPUT]
    name              tail
    path              /var/log/apt/*.log

[OUTPUT]
    Name file
    Path /var/log/fluent-bit/apt
    Format template
    Mkdir true
    Template {time} used={Mem.used} free={Mem.free} total={Mem.total}
