[INPUT]
    name              tail
    path              /template/var/log/datadog/agent.log
    Read_from_Head true
    Refresh_Interval 10
    parser datadog-agent

[INPUT]
    name              tail
    path              /template/var/log/datadog/init.log
    Read_from_Head true
    Refresh_Interval 10
    parser datadog-init

[INPUT]
    name              tail
    path              /template/var/log/datadog/process-agent.log
    Read_from_Head true
    Refresh_Interval 10
    parser datadog-process-agent

[INPUT]
    name              tail
    path              /template/var/log/datadog/security-agent.log
    Read_from_Head true
    Refresh_Interval 10
    parser datadog-security-agent

[INPUT]
    name              tail
    path              /template/var/log/datadog/system-probe.log
    Read_from_Head true
    Refresh_Interval 10
    parser datadog-system-probe

[INPUT]
    name              tail
    path              /template/var/log/datadog/agent-health.log
    Read_from_Head    true
    Refresh_Interval  10
    multiline.parser  datadog-agent-health

[OUTPUT]
    Name file
    Path /var/log/fluent-bit/datadog
    Match *
    Mkdir true
