FROM ubuntu:18.04

RUN \
    apt-get update \
    && apt-get install -y \
        octave \
        less

# RUN \
#     apt-get udpate \
#     && apt-get install -y \
#         flatpak \
#     && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo \
#     && flatpak install flathub org.octave.Octave \
