include ../script/make/build_directory.mk

build-ubuntu:
	make --directory=docker-pyspark-ubuntu-16.04

build-alpine:
	make --directory=docker-pyspark-alpine

build-alpine-spark-history-server:
	make --directory=docker-pyspark-alpine-spark-history-server

build-centos7.5.1804:
	make --directory=docker-pyspark-centos7.5.1804
