# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _example
else:
    import _example

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class List(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _example.List_swiginit(self, _example.new_List())
    __swig_destroy__ = _example.delete_List

    def search(self, value):
        return _example.List_search(self, value)

    def insert(self, value):
        return _example.List_insert(self, value)

    def remove(self, value):
        return _example.List_remove(self, value)

    def get(self, n):
        return _example.List_get(self, n)

    @staticmethod
    def _print(l):
        return _example.List__print(l)
    length = property(_example.List_length_get, _example.List_length_set)

# Register List in _example:
_example.List_swigregister(List)

def List__print(l):
    return _example.List__print(l)


def new_list():
    return _example.new_list()

def delete_list(l):
    return _example.delete_list(l)
class Foo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _example.Foo_swiginit(self, _example.new_Foo())
    __swig_destroy__ = _example.delete_Foo

    def bar(self, x):
        return _example.Foo_bar(self, x)
    x = property(_example.Foo_x_get, _example.Foo_x_set)

# Register Foo in _example:
_example.Foo_swigregister(Foo)


def fact(n):
    return _example.fact(n)


